import { iwsdkDev } from "@iwsdk/vite-plugin-dev";
import { compileUIKit } from "@iwsdk/vite-plugin-uikitml";
import { optimizeGLTF } from "@iwsdk/vite-plugin-gltf-optimizer";
import type { Plugin } from "vite";
import { defineConfig, loadEnv } from "vite";
import mkcert from "vite-plugin-mkcert";
import { VitePWA } from "vite-plugin-pwa";
import fs from "fs";
import path from "path";

/**
 * nvidiaKeyPlugin — Injects VITE_AI_API_KEY into the isolated AI Assistant
 * page without bundling.
 *
 * Because public/ai-assistant/* files are served as static assets (not
 * processed by Vite's module graph), import.meta.env is unavailable inside
 * them. This plugin intercepts GET /ai-assistant/env.js and responds with a
 * tiny inline script that sets window.__NVIDIA_API_KEY__ at runtime.
 *
 * In production builds it writes the same script as a static file so it is
 * included in the dist/ output.
 */
function nvidiaKeyPlugin(apiKey: string): Plugin {
  const VIRTUAL_PATH = "/ai-assistant/env.js";

  /** The generated script content — key intentionally short-lived per request */
  const envScript = (): string =>
    `// Auto-generated by nvidiaKeyPlugin — do not edit manually.\n` +
    `// Contains a runtime-scoped API key for the AI Assistant sandbox page.\n` +
    `window.__NVIDIA_API_KEY__ = ${JSON.stringify(apiKey || "")};\n`;

  // NOTE: No `apply` restriction — configureServer is a dev-only hook by
  // design (Vite never calls it during builds), and generateBundle is a
  // build-only hook. Having both in one plugin object is safe and idiomatic.
  return {
    name: "vite-plugin-nvidia-key",

    // DEV: intercept GET /ai-assistant/env.js and serve it dynamically
    configureServer(server) {
      // Return a function so our handler is appended AFTER Vite's own
      // internal middleware, ensuring static-file handlers run first.
      return () => {
        server.middlewares.use((req, res, next) => {
          if (req.url === VIRTUAL_PATH || req.url?.startsWith(VIRTUAL_PATH + "?")) {
            res.setHeader("Content-Type", "application/javascript; charset=utf-8");
            res.setHeader("Cache-Control", "no-store");
            res.end(envScript());
          } else {
            next();
          }
        });
      };
    },

    // BUILD: emit env.js as a static asset included in dist/
    // NOTE: For production deployments rotate/proxy the key server-side.
    // Never commit a long-lived secret in a public build artifact.
    generateBundle() {
      // In production builds, we completely exclude/delete ai-assistant folder.
      // So do not write the env.js file.
    },
  };
}

/**
 * cleanPublicAssetsPlugin — Deletes dist/ai-assistant/ post-build so it is
 * never deployed to Netlify or any production server.
 */
function cleanPublicAssetsPlugin(): Plugin {
  return {
    name: "vite-plugin-clean-public-assets",
    apply: "build", // only run during build
    closeBundle() {
      const folderPath = path.resolve(process.cwd(), "dist/ai-assistant");
      if (fs.existsSync(folderPath)) {
        fs.rmSync(folderPath, { recursive: true, force: true });
        console.log("🧹 Cleaned up dist/ai-assistant from build output.");
      }
    }
  };
}

export default defineConfig(({ mode }) => {
  // Load .env variables for the current mode so they are available here
  const env = loadEnv(mode, process.cwd(), "");
  const apiKey = env.VITE_AI_API_KEY ?? "";

  return {
    plugins: [
      mkcert(),
      iwsdkDev({
        emulator: {
          device: "metaQuest3",
          // 'always' so the XR emulator is injected on Netlify and any other
          // production domain — not just localhost. Without this, desktop
          // browsers on the deployed site have no WebXR and the Enter XR
          // button never appears.
          activation: "always",
          // Inject the emulator into the production bundle (dist/).
          // The userAgentException below ensures real Quest browsers skip
          // the emulator and use native WebXR instead.
          injectOnBuild: true,
          // Skip injection on actual Meta Quest / OculusBrowser so headsets
          // use native WebXR (not the emulated one).
          userAgentException: /OculusBrowser/,
        },
        ai: { tools: ["claude"] },
        verbose: true,
      }),

      compileUIKit({ sourceDir: "ui", outputDir: "public/ui", verbose: true }),

      optimizeGLTF({
        level: "medium",
        verbose: true,
      }),

      // AI Assistant sandbox — key injection middleware
      nvidiaKeyPlugin(apiKey),

      cleanPublicAssetsPlugin(),

      // PWA setup for Web Share Target
      VitePWA({
        strategies: 'injectManifest',
        srcDir: 'src',
        filename: 'sw.ts',
        injectManifest: {
          injectionPoint: undefined,
        },
        devOptions: {
          enabled: true,
          type: 'module',
        },
        manifest: {
          name: 'Lathe Trainer',
          short_name: 'LatheTrainer',
          theme_color: '#1a1a1a',
          background_color: '#1a1a1a',
          display: 'standalone',
          share_target: {
            action: '/share-target',
            method: 'POST',
            enctype: 'multipart/form-data',
            params: {
              files: [
                {
                  name: 'image',
                  accept: ['image/*']
                }
              ]
            }
          }
        }
      }),
    ],
    server: {
      host: "0.0.0.0",
      port: 8081,
      open: true,
      proxy: {
        "/v1": {
          target: "https://integrate.api.nvidia.com",
          changeOrigin: true,
          secure: true,
        },
      },
    },
    build: {
      outDir: "dist",
      sourcemap: process.env.NODE_ENV !== "production",
      target: "esnext",
      rollupOptions: {
        input: {
          main: "./index.html",
          aiSandbox: "./ai-sandbox.html",
        },
      },
    },
    esbuild: { target: "esnext" },
    optimizeDeps: {
      exclude: ["@babylonjs/havok"],
      esbuildOptions: { target: "esnext" },
    },
    publicDir: "public",
    base: "./",
  };
});
